# Name of the workflow
name: Automated Update of Named Cache

# Define the events that trigger the workflow
on:
  # Trigger the workflow on a schedule (every day at midnight)
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering of the workflow
  workflow_dispatch:

# Define the jobs in the workflow
jobs:
  # Define a job named "build"
  build:
    # Name of the job that will be displayed on GitHub
    name: Refresh Named Cache
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment variables available to all steps in the job
    env:
      NAMED_CACHE_URL: https://www.internic.net/domain/named.cache
      NAMED_CACHE_PATH: assets/named.cache

    steps:
      # Check out the repository code
      - name: Check out code
        uses: actions/checkout@v5 # Updated to use the latest version for better compatibility and features

      # Get the current SHA-3-512 hash of the file
      - name: Get current hash
        run: |
          echo "NAMED_CACHE_CURRENT_HASH=$(openssl dgst -sha3-512 "${{ env.NAMED_CACHE_PATH }}" | awk '{print $2}')" >> $GITHUB_ENV

      # Get the future SHA-3-512 hash of the file
      - name: Get future hash
        run: |
          echo "NAMED_CACHE_FUTURE_HASH=$(curl --silent "${{ env.NAMED_CACHE_URL }}" | openssl dgst -sha3-512 | awk '{print $2}')" >> $GITHUB_ENV

      # Check if an update is needed
      - name: Check for update
        run: |
          if [ "$NAMED_CACHE_CURRENT_HASH" != "$NAMED_CACHE_FUTURE_HASH" ]; then
            curl -o "${{ env.NAMED_CACHE_PATH }}" "${{ env.NAMED_CACHE_URL }}"
          else
            echo "No update needed"
            exit 0
          fi

      # Push the updated file to GitHub
      - name: Push updated named.cache
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if git diff --exit-code --quiet -- "${{ env.NAMED_CACHE_PATH }}"; then
            echo "No changes to commit"
            exit 0
          else
            git add "${{ env.NAMED_CACHE_PATH }}"
            git commit -m "Update named.cache $(date)"
            git push
          fi
